//! OpenClaw automatic configuration.
//!
//! Generates an OpenClaw plugin under `~/.openclaw/extensions/nevoflux-tools/`
//! that bridges NevoFlux tools to OpenClaw via HTTP MCP.
//!
//! The plugin reads the MCP server URL from a state file written by the daemon,
//! then proxies tool calls to the same HTTP MCP server used by Claude Code and
//! Gemini CLI — ensuring consistent tool execution across all ACP providers.

use std::ffi::OsString;
use std::process::Command;

/// Well-known path for the MCP server URL state file.
/// Written by the daemon when the HTTP MCP server starts.
const MCP_URL_FILENAME: &str = "openclaw_mcp_url";

/// Resolve the `openclaw` binary to its full path.
pub fn resolve_openclaw() -> OsString {
    let search_path = nevoflux_llm::util::build_search_path();
    which::which_in(
        "openclaw",
        search_path.as_deref(),
        std::env::current_dir().unwrap_or_default(),
    )
    .map(|p| p.into_os_string())
    .unwrap_or_else(|_| OsString::from("openclaw"))
}

/// Check if OpenClaw CLI is installed.
pub fn is_openclaw_installed() -> bool {
    let search_path = nevoflux_llm::util::build_search_path();
    which::which_in(
        "openclaw",
        search_path.as_deref(),
        std::env::current_dir().unwrap_or_default(),
    )
    .is_ok()
}

/// Write the MCP server URL to a well-known state file so the OpenClaw plugin
/// can discover it at runtime.
pub fn write_mcp_url(url: &str) -> Result<(), String> {
    let state_dir = dirs::config_dir()
        .ok_or_else(|| "Cannot determine config directory".to_string())?
        .join("nevoflux");
    std::fs::create_dir_all(&state_dir)
        .map_err(|e| format!("Failed to create config dir: {}", e))?;
    std::fs::write(state_dir.join(MCP_URL_FILENAME), url)
        .map_err(|e| format!("Failed to write MCP URL state file: {}", e))?;
    tracing::info!("Wrote MCP URL to state file: {}", url);
    Ok(())
}

/// Disable OpenClaw's built-in browser tool by adding "browser" to tools.deny.
pub fn disable_openclaw_browser() -> Result<(), String> {
    let existing = Command::new(resolve_openclaw())
        .args(["config", "get", "tools.deny"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                let s = String::from_utf8_lossy(&o.stdout).trim().to_string();
                serde_json::from_str::<Vec<String>>(&s).ok()
            } else {
                None
            }
        })
        .unwrap_or_default();

    let mut deny_list = existing;
    // Deny OpenClaw's built-in tools that conflict with NevoFlux plugin tools.
    // "browser" disables the entire browser group; individual names cover
    // tools outside the group that still clash.
    for name in ["browser", "browser_get_markdown", "web_search"] {
        if !deny_list.iter().any(|s| s == name) {
            deny_list.push(name.to_string());
        }
    }

    let output = Command::new(resolve_openclaw())
        .args([
            "config",
            "set",
            "tools.deny",
            &serde_json::to_string(&deny_list).unwrap(),
            "--strict-json",
        ])
        .output()
        .map_err(|e| format!("Failed to set tools.deny: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("tools.deny set failed: {}", stderr));
    }
    tracing::info!("Disabled OpenClaw built-in browser tool");
    Ok(())
}

/// Generate the OpenClaw plugin TypeScript file.
///
/// The plugin registers NevoFlux browser/computer tools as OpenClaw agent tools.
/// Each tool's `execute` function proxies calls to the NevoFlux HTTP MCP server.
fn generate_plugin_index() -> String {
    let config_dir = dirs::config_dir()
        .map(|d| d.join("nevoflux"))
        .unwrap_or_default();
    let mcp_url_path = config_dir.join(MCP_URL_FILENAME);
    // Escape backslashes for Windows paths in TypeScript string
    let mcp_url_path_str = mcp_url_path.to_string_lossy().replace('\\', "\\\\");

    format!(
        r#"// Auto-generated by NevoFlux — do not edit manually.
// This plugin bridges NevoFlux browser/computer tools to OpenClaw
// via the same HTTP MCP server used by Claude Code and Gemini CLI.

import {{ definePluginEntry }} from "openclaw/plugin-sdk/plugin-entry";
import {{ Type }} from "@sinclair/typebox";
import {{ readFileSync }} from "node:fs";

const MCP_URL_PATH = "{mcp_url_path}";

function getMcpUrl(): string | null {{
  try {{
    return readFileSync(MCP_URL_PATH, "utf-8").trim();
  }} catch {{
    return null;
  }}
}}

async function callMcpTool(name: string, args: Record<string, unknown>): Promise<string> {{
  const url = getMcpUrl();
  if (!url) {{
    return "NevoFlux MCP server is not running. Please start NevoFlux first.";
  }}
  const body = JSON.stringify({{
    jsonrpc: "2.0",
    id: Date.now(),
    method: "tools/call",
    params: {{ name, arguments: args }},
  }});
  const resp = await fetch(url, {{
    method: "POST",
    headers: {{ "Content-Type": "application/json" }},
    body,
  }});
  const json = await resp.json() as any;
  if (json.error) {{
    return `Tool error: ${{json.error.message || JSON.stringify(json.error)}}`;
  }}
  const content = json.result?.content;
  if (Array.isArray(content)) {{
    return content.map((c: any) => c.text || JSON.stringify(c)).join("\n");
  }}
  return JSON.stringify(json.result);
}}

// Register with "nf_" prefix to avoid conflicts with OpenClaw built-in tools.
// MCP calls use the original name (without prefix).
function tool(mcpName: string, description: string, parameters: any) {{
  return {{
    name: `nf_${{mcpName}}`,
    description: `[NevoFlux] ${{description}}`,
    parameters,
    async execute(_id: string, params: any) {{
      const text = await callMcpTool(mcpName, params ?? {{}});
      return {{ content: [{{ type: "text" as const, text }}] }};
    }},
  }};
}}

export default definePluginEntry({{
  id: "nevoflux-tools",
  name: "NevoFlux Tools",
  description: "Browser automation, computer control, and web tools powered by NevoFlux",
  register(api) {{
    // Browser tools
    api.registerTool(tool("browser_get_markdown", "Read current page content as Markdown", Type.Object({{
      tab_id: Type.Optional(Type.Number({{ description: "Browser tab ID" }})),
    }})));
    api.registerTool(tool("browser_navigate", "Navigate browser to a URL", Type.Object({{
      url: Type.String({{ description: "URL to navigate to" }}),
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_click_by_id", "Click page element by snapshot ref ID", Type.Object({{
      element_id: Type.String({{ description: "Element ref ID from snapshot (e.g. 'e5')" }}),
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_snapshot", "Get page accessibility tree with element ref IDs", Type.Object({{
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_screenshot", "Take screenshot of current page", Type.Object({{
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_scroll", "Scroll page up or down", Type.Object({{
      direction: Type.String({{ description: "'up' or 'down'" }}),
      amount: Type.Optional(Type.String({{ description: "'page', 'half', or pixel number" }})),
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_get_tabs", "List all open browser tabs", Type.Object({{}})));
    api.registerTool(tool("browser_get_content", "Get page HTML source", Type.Object({{
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_eval_js", "Execute JavaScript on current page", Type.Object({{
      code: Type.String({{ description: "JavaScript code to execute" }}),
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_fill_by_id", "Fill form field by ref ID", Type.Object({{
      element_id: Type.String(),
      value: Type.String(),
      tab_id: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("browser_type_by_id", "Type text into element by ref ID", Type.Object({{
      element_id: Type.String(),
      text: Type.String(),
      tab_id: Type.Optional(Type.Number()),
    }})));
    // Web tools
    api.registerTool(tool("web_search", "Search the web", Type.Object({{
      query: Type.String({{ description: "Search query" }}),
    }})));
    api.registerTool(tool("fetch_page", "Fetch URL content as markdown", Type.Object({{
      url: Type.String({{ description: "URL to fetch" }}),
    }})));

    // Artifact
    api.registerTool(tool("create_artifact", "Create interactive Canvas app (HTML/React/SVG/Mermaid)", Type.Object({{
      title: Type.String({{ description: "Artifact title" }}),
      files: Type.Record(Type.String(), Type.String(), {{ description: "filename -> content map" }}),
      type: Type.Optional(Type.String({{ description: "html, react, svg, mermaid, markdown" }})),
    }})));

    // Computer tools
    api.registerTool(tool("computer_screenshot", "Take screenshot of entire screen", Type.Object({{
      monitor: Type.Optional(Type.Number()),
    }})));
    api.registerTool(tool("computer_click", "Click at screen position", Type.Object({{
      x: Type.Number(), y: Type.Number(),
      button: Type.Optional(Type.String()),
    }})));
    api.registerTool(tool("computer_type_text", "Type text at current cursor", Type.Object({{
      text: Type.String(),
    }})));
    api.registerTool(tool("computer_key", "Press keyboard keys", Type.Object({{
      keys: Type.String({{ description: "Key combination e.g. 'ctrl+c'" }}),
    }})));
    api.registerTool(tool("computer_mouse_move", "Move mouse to position", Type.Object({{
      x: Type.Number(), y: Type.Number(),
    }})));
    api.registerTool(tool("computer_scroll", "Scroll at screen position", Type.Object({{
      x: Type.Number(), y: Type.Number(),
      direction: Type.String(),
      amount: Type.Optional(Type.Number()),
    }})));
  }},
}});
"#,
        mcp_url_path = mcp_url_path_str,
    )
}

/// Generate the OpenClaw plugin manifest file.
fn generate_plugin_manifest() -> String {
    r#"{
  "id": "nevoflux-tools",
  "name": "NevoFlux Tools",
  "description": "Browser automation, computer control, and web tools powered by NevoFlux",
  "configSchema": {
    "type": "object",
    "additionalProperties": false
  }
}
"#
    .to_string()
}

/// Generate the plugin package.json.
fn generate_plugin_package_json() -> String {
    r#"{
  "name": "nevoflux-tools",
  "version": "1.0.0",
  "type": "module",
  "openclaw": {
    "extensions": ["./index.ts"]
  }
}
"#
    .to_string()
}

/// Find the OpenClaw npm package directory for symlinking.
fn find_openclaw_package_dir() -> Option<std::path::PathBuf> {
    let search_path = nevoflux_llm::util::build_search_path();
    let openclaw_bin = which::which_in(
        "openclaw",
        search_path.as_deref(),
        std::env::current_dir().unwrap_or_default(),
    )
    .ok()?;
    // openclaw binary is typically at <prefix>/bin/openclaw or <prefix>/lib/node_modules/openclaw/...
    // Follow symlinks to find the actual package directory
    let resolved = std::fs::canonicalize(&openclaw_bin).unwrap_or(openclaw_bin);
    // Walk up to find package.json with name "openclaw"
    let mut dir = resolved.parent()?;
    for _ in 0..10 {
        let pkg_json = dir.join("package.json");
        if pkg_json.exists() {
            if let Ok(content) = std::fs::read_to_string(&pkg_json) {
                if let Ok(parsed) = serde_json::from_str::<serde_json::Value>(&content) {
                    if parsed.get("name").and_then(|n| n.as_str()) == Some("openclaw") {
                        return Some(dir.to_path_buf());
                    }
                }
            }
        }
        dir = dir.parent()?;
    }
    None
}

/// Install the NevoFlux tools plugin into OpenClaw extensions directory.
fn install_plugin() -> Result<(), String> {
    let plugin_dir = dirs::home_dir()
        .ok_or_else(|| "Cannot determine home directory".to_string())?
        .join(".openclaw/extensions/nevoflux-tools");

    std::fs::create_dir_all(&plugin_dir)
        .map_err(|e| format!("Failed to create plugin directory: {}", e))?;

    std::fs::write(plugin_dir.join("index.ts"), generate_plugin_index())
        .map_err(|e| format!("Failed to write index.ts: {}", e))?;
    std::fs::write(
        plugin_dir.join("openclaw.plugin.json"),
        generate_plugin_manifest(),
    )
    .map_err(|e| format!("Failed to write manifest: {}", e))?;
    std::fs::write(
        plugin_dir.join("package.json"),
        generate_plugin_package_json(),
    )
    .map_err(|e| format!("Failed to write package.json: {}", e))?;

    // Create node_modules symlinks so the plugin can import openclaw SDK.
    // Extensions outside the openclaw monorepo need the openclaw package
    // in their local node_modules for module resolution.
    let nm_dir = plugin_dir.join("node_modules");
    let _ = std::fs::create_dir_all(&nm_dir);
    if let Some(openclaw_pkg) = find_openclaw_package_dir() {
        let openclaw_link = nm_dir.join("openclaw");
        if !openclaw_link.exists() {
            #[cfg(unix)]
            let _ = std::os::unix::fs::symlink(&openclaw_pkg, &openclaw_link);
            #[cfg(windows)]
            let _ = std::os::windows::fs::symlink_dir(&openclaw_pkg, &openclaw_link);
        }
        // Also link @sinclair/typebox (used for parameter schemas)
        let sinclair_src = openclaw_pkg.join("node_modules/@sinclair");
        if sinclair_src.exists() {
            let sinclair_link = nm_dir.join("@sinclair");
            if !sinclair_link.exists() {
                #[cfg(unix)]
                let _ = std::os::unix::fs::symlink(&sinclair_src, &sinclair_link);
                #[cfg(windows)]
                let _ = std::os::windows::fs::symlink_dir(&sinclair_src, &sinclair_link);
            }
        }
    }

    tracing::info!("Installed NevoFlux tools plugin to {:?}", plugin_dir);
    Ok(())
}

/// Check if OpenClaw gateway is running.
pub fn is_gateway_running() -> bool {
    Command::new(resolve_openclaw())
        .args(["health"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Start OpenClaw gateway in the background.
pub fn start_gateway() -> Result<(), String> {
    if is_gateway_running() {
        return Ok(()); // Already running
    }
    // Use `openclaw gateway` which handles daemonization internally
    let output = Command::new(resolve_openclaw())
        .args(["gateway", "--port", "18789"])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to start gateway: {}", e))?;
    drop(output); // Detach — gateway runs independently
                  // Wait for gateway to become healthy
    for _ in 0..10 {
        std::thread::sleep(std::time::Duration::from_secs(1));
        if is_gateway_running() {
            tracing::info!("OpenClaw gateway started");
            return Ok(());
        }
    }
    Err("Gateway started but not responding after 10s".to_string())
}

/// Restart OpenClaw gateway (needed after plugin install).
fn restart_gateway() {
    // Kill existing gateway, let start_gateway() spawn a new one
    let _ = Command::new(resolve_openclaw())
        .args(["gateway", "stop"])
        .output();
    std::thread::sleep(std::time::Duration::from_secs(2));
    let _ = start_gateway();
}

/// Check if NevoFlux plugin is installed in OpenClaw extensions.
pub fn is_plugin_installed() -> bool {
    dirs::home_dir()
        .map(|h| {
            h.join(".openclaw/extensions/nevoflux-tools/index.ts")
                .exists()
        })
        .unwrap_or(false)
}

/// Write OpenClaw auth profile for a provider.
pub fn write_auth_profile(provider_name: &str, api_key: &str) -> Result<(), String> {
    if api_key.is_empty() {
        return Ok(());
    }
    let home = dirs::home_dir().ok_or("Cannot determine home directory")?;
    let auth_path = home.join(".openclaw/agents/main/agent/auth-profiles.json");

    let mut profiles: serde_json::Value = std::fs::read_to_string(&auth_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| serde_json::json!({"profiles": {}}));

    let profile_key = format!("{}:default", provider_name);
    if let Some(obj) = profiles.get_mut("profiles").and_then(|p| p.as_object_mut()) {
        obj.insert(
            profile_key,
            serde_json::json!({
                "type": "api_key",
                "provider": provider_name,
                "key": api_key,
            }),
        );
    }

    if let Some(parent) = auth_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    std::fs::write(&auth_path, serde_json::to_string_pretty(&profiles).unwrap())
        .map_err(|e| format!("Failed to write auth-profiles.json: {}", e))?;
    tracing::info!("Wrote OpenClaw auth profile for '{}'", provider_name);
    Ok(())
}

/// Full auto-setup: install plugin, configure permissions, start gateway.
/// Called from handle_openclaw_model_set after saving model config.
/// Returns (needs_browser_restart, message).
pub fn full_auto_setup() -> (bool, String) {
    let mut steps: Vec<String> = Vec::new();
    let mut needs_restart = false;

    // Step 1: Install plugin if needed
    if !is_plugin_installed() {
        match install_plugin() {
            Ok(()) => {
                steps.push("Installed NevoFlux tools plugin".to_string());
                needs_restart = true;
            }
            Err(e) => return (false, format!("Failed to install plugin: {}", e)),
        }
    }

    // Step 2: Configure tools.deny (disable conflicting built-in tools)
    let _ = disable_openclaw_browser();

    // Step 3: Enable plugin in plugins.allow
    let _ = Command::new(resolve_openclaw())
        .args([
            "config",
            "set",
            "plugins.allow",
            r#"["nevoflux-tools"]"#,
            "--strict-json",
        ])
        .output();

    // Step 4: Start or restart gateway
    if needs_restart || !is_gateway_running() {
        if is_gateway_running() {
            steps.push("Restarting gateway to load plugin".to_string());
            restart_gateway();
        } else {
            match start_gateway() {
                Ok(()) => steps.push("Started OpenClaw gateway".to_string()),
                Err(e) => steps.push(format!("Gateway start failed: {}", e)),
            }
        }
    }

    if steps.is_empty() {
        (false, "OpenClaw already configured".to_string())
    } else {
        (needs_restart, steps.join("; "))
    }
}

/// Run OpenClaw setup — installs NevoFlux tools plugin.
/// Called when OpenClaw ACP session starts (before connect).
///
/// Returns Ok(true) if first-time setup was performed, Ok(false) if already configured.
pub fn ensure_openclaw_configured() -> Result<bool, String> {
    if !is_openclaw_installed() {
        return Err(
            "OpenClaw is not installed. Install with: npm install -g openclaw@latest && openclaw onboard"
                .to_string(),
        );
    }

    if is_plugin_installed() {
        return Ok(false); // Already configured
    }

    // First-time setup (via full_auto_setup)
    let (_, msg) = full_auto_setup();
    tracing::info!("OpenClaw first-time setup: {}", msg);
    Ok(true)
}
