//! Skills integration for the daemon.

use crate::error::{DaemonError, Result};
use nevoflux_skills::{LoaderConfig, Skill, SkillRegistry, SkillSummary};
use std::sync::Arc;
use tokio::sync::RwLock;

/// Skills manager for the daemon.
pub struct SkillsManager {
    registry: Arc<RwLock<SkillRegistry>>,
    config: LoaderConfig,
}

impl SkillsManager {
    /// Create a new skills manager.
    pub fn new() -> Self {
        Self {
            registry: Arc::new(RwLock::new(SkillRegistry::new())),
            config: LoaderConfig::new(),
        }
    }

    /// Create with custom config.
    pub fn with_config(config: LoaderConfig) -> Self {
        Self {
            registry: Arc::new(RwLock::new(SkillRegistry::with_config(config.clone()))),
            config,
        }
    }

    /// Load skills from configured directories.
    pub async fn load(&self) -> Result<usize> {
        let mut registry = self.registry.write().await;
        registry
            .load()
            .map_err(|e| DaemonError::InternalError(format!("Failed to load skills: {}", e)))?;
        Ok(registry.len())
    }

    /// Re-scan the configured skill directories, replacing the registry's
    /// contents. Used after a pack places or removes skill files so installs
    /// activate without a daemon restart.
    pub async fn reload(&self) -> Result<usize> {
        let mut registry = self.registry.write().await;
        registry
            .reload()
            .map_err(|e| DaemonError::InternalError(format!("Failed to reload skills: {}", e)))?;
        Ok(registry.len())
    }

    /// List all available skills (Level 1).
    pub async fn list(&self) -> Vec<SkillSummary> {
        let registry = self.registry.read().await;
        registry.list()
    }

    /// Get a skill by name (Level 2).
    pub async fn get(&self, name: &str) -> Option<Skill> {
        let registry = self.registry.read().await;
        registry.get(name).cloned()
    }

    /// Get the number of loaded skills.
    pub async fn len(&self) -> usize {
        let registry = self.registry.read().await;
        registry.len()
    }

    /// Check if no skills are loaded.
    pub async fn is_empty(&self) -> bool {
        self.len().await == 0
    }

    /// Get the registry (for advanced use).
    pub fn registry(&self) -> Arc<RwLock<SkillRegistry>> {
        self.registry.clone()
    }

    /// Get the loader configuration.
    pub fn config(&self) -> &LoaderConfig {
        &self.config
    }
}

impl Default for SkillsManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_skills_manager_creation() {
        let manager = SkillsManager::new();
        assert!(manager.is_empty().await);
    }

    #[tokio::test]
    async fn test_skills_manager_list_empty() {
        let manager = SkillsManager::new();
        let skills = manager.list().await;
        assert!(skills.is_empty());
    }

    #[tokio::test]
    async fn test_skills_manager_get_not_found() {
        let manager = SkillsManager::new();
        let skill = manager.get("nonexistent").await;
        assert!(skill.is_none());
    }

    #[tokio::test]
    async fn reload_rescans_registry_without_panicking() {
        let mgr = SkillsManager::new();
        // First load (may find 0 skills in a clean test env — that's fine).
        let _ = mgr.load().await;
        // reload() must succeed and return the current count.
        let count = mgr.reload().await.expect("reload should succeed");
        assert_eq!(count, mgr.len().await);
    }

    /// The premise behind `HostServices::ensure_skill_or_reload`: a skill file
    /// written *after* the registry's initial load (e.g. one just generated by
    /// skill-creator from a recording) is invisible to a cached registry but
    /// becomes resolvable after a `reload()` — no daemon restart required.
    #[tokio::test]
    async fn reload_picks_up_skill_created_after_initial_load() {
        use std::io::Write;

        let temp = tempfile::tempdir().expect("create temp skills dir");
        let cfg = LoaderConfig::new().with_user_dir(temp.path().to_path_buf());
        let mgr = SkillsManager::with_config(cfg);

        // Initial load over an empty dir: the new skill does not exist yet.
        let initial = mgr.load().await.expect("initial load");
        assert_eq!(initial, 0, "temp registry should start empty");
        assert!(mgr.get("demo-after-load").await.is_none());

        // Simulate skill-creator writing a new skill into the user skills dir
        // while the daemon is already running.
        let skill_dir = temp.path().join("demo-after-load");
        std::fs::create_dir_all(&skill_dir).expect("create skill subdir");
        let mut f =
            std::fs::File::create(skill_dir.join("SKILL.md")).expect("create SKILL.md");
        write!(
            f,
            "---\nname: demo-after-load\ndescription: A skill written after the registry was first loaded.\n---\n\n# Demo\n\nBody.\n"
        )
        .expect("write SKILL.md");

        // Still invisible: the registry holds the startup snapshot.
        assert!(
            mgr.get("demo-after-load").await.is_none(),
            "new skill must be invisible until the registry is rescanned"
        );

        // reload() makes it resolvable without a restart — this is exactly what
        // ensure_skill_or_reload performs on a lookup miss.
        let after = mgr.reload().await.expect("reload");
        assert_eq!(after, 1, "reload must pick up the newly written skill");
        assert!(
            mgr.get("demo-after-load").await.is_some(),
            "skill must resolve after reload"
        );
    }
}
