// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! OAuth callback registry — one persistent listener replaces N
//! ephemeral OAuth callback servers (Anthropic OAuth, MCP server OAuth,
//! ...).
//!
//! Lifecycle:
//! 1. Originator calls [`AssetServer::register_oauth_flow`], gets back
//!    `(callback_url, oneshot::Receiver<OAuthCallbackResult>)`. The
//!    state param is generated by the originator; the registry maps it
//!    to the oneshot sender + expected provider name.
//! 2. Originator builds the OAuth authorize URL with `state` +
//!    `redirect_uri = callback_url` and opens it in the browser.
//! 3. After the user grants access, the provider redirects to the
//!    callback URL. The asset server's `/v1/oauth/:provider/callback`
//!    handler looks up `state` in the registry and forwards the
//!    `(code, state, error, error_description)` tuple via the oneshot.
//! 4. Originator awaits the oneshot, exchanges `code` for a token via
//!    the provider's token endpoint (with the originator's own
//!    client_secret + provider-specific endpoint URL), and proceeds
//!    with the access token.
//!
//! The asset server is intentionally a dumb pipe: it doesn't know
//! provider-specific token endpoints, client credentials, or token
//! formats. Each originator owns that knowledge — same separation of
//! concerns as the rest of the asset plane (D2: no strong-semantics
//! RPC on the HTTP plane).

use std::sync::Arc;
use std::time::{Duration, Instant};

use dashmap::DashMap;
use tokio::sync::oneshot;

/// Result the asset server hands back to the originator when an OAuth
/// callback arrives. Either `code` is present (success) or `error` is
/// present (provider rejected). Originator dispatches accordingly.
#[derive(Debug, Clone)]
pub struct OAuthCallbackResult {
    pub provider: String,
    pub state: String,
    pub code: Option<String>,
    pub error: Option<String>,
    pub error_description: Option<String>,
}

/// Pending OAuth flow — kept until the callback arrives or TTL expires.
struct OAuthPending {
    expected_provider: String,
    tx: oneshot::Sender<OAuthCallbackResult>,
    expires_at: Instant,
}

/// Thread-safe registry for in-flight OAuth flows, keyed by `state`.
///
/// `state` is the OAuth-spec CSRF token: a random value the originator
/// generates and embeds in the authorize URL. The provider echoes it
/// back in the callback. We use it as the registry key, which gives
/// the same single-use guarantee as the legacy `/file/:token` UUID.
pub struct OAuthRegistry {
    pending: DashMap<String, OAuthPending>,
}

impl Default for OAuthRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl OAuthRegistry {
    pub fn new() -> Self {
        Self {
            pending: DashMap::new(),
        }
    }

    /// Park a pending flow. `state` MUST be the same value the
    /// originator embedded in the authorize URL `state=` parameter.
    pub fn register(
        &self,
        provider: impl Into<String>,
        state: impl Into<String>,
        ttl: Duration,
    ) -> oneshot::Receiver<OAuthCallbackResult> {
        let (tx, rx) = oneshot::channel();
        self.pending.insert(
            state.into(),
            OAuthPending {
                expected_provider: provider.into(),
                tx,
                expires_at: Instant::now() + ttl,
            },
        );
        rx
    }

    /// Resolve a pending flow with the callback result. Returns `true`
    /// if the state was registered AND the provider matched (i.e. the
    /// call dispatched a result); `false` if the state is unknown,
    /// expired, or the provider doesn't match.
    pub fn resolve(&self, result: OAuthCallbackResult) -> bool {
        let entry = match self.pending.remove(&result.state) {
            Some((_, e)) => e,
            None => return false,
        };
        if Instant::now() > entry.expires_at {
            return false;
        }
        if entry.expected_provider != result.provider {
            return false;
        }
        // Best-effort: the receiver may have been dropped if the
        // originator gave up early. We still consider this a "resolve"
        // because the registry entry was consumed.
        let _ = entry.tx.send(result);
        true
    }

    /// Reap entries past their deadline.
    pub fn sweep_expired(&self) {
        let now = Instant::now();
        self.pending.retain(|_, p| p.expires_at > now);
    }

    pub fn len(&self) -> usize {
        self.pending.len()
    }

    pub fn is_empty(&self) -> bool {
        self.pending.is_empty()
    }
}

/// Spawn a detached eviction loop that periodically reaps expired
/// pending flows. Same pattern as `token_store::spawn_eviction_loop`.
pub fn spawn_oauth_eviction_loop(registry: Arc<OAuthRegistry>, interval: Duration) {
    tokio::spawn(async move {
        let mut ticker = tokio::time::interval(interval);
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        ticker.tick().await;
        loop {
            ticker.tick().await;
            if Arc::strong_count(&registry) == 1 {
                break;
            }
            registry.sweep_expired();
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn register_then_resolve_delivers_result() {
        let reg = OAuthRegistry::new();
        let rx = reg.register("anthropic", "state-1", Duration::from_secs(30));
        assert_eq!(reg.len(), 1);

        let ok = reg.resolve(OAuthCallbackResult {
            provider: "anthropic".into(),
            state: "state-1".into(),
            code: Some("auth-code".into()),
            error: None,
            error_description: None,
        });
        assert!(ok);
        assert!(reg.is_empty(), "resolve must consume the entry");

        let result = rx.await.unwrap();
        assert_eq!(result.code.as_deref(), Some("auth-code"));
    }

    #[tokio::test]
    async fn resolve_unknown_state_returns_false() {
        let reg = OAuthRegistry::new();
        let ok = reg.resolve(OAuthCallbackResult {
            provider: "anthropic".into(),
            state: "never-registered".into(),
            code: Some("x".into()),
            error: None,
            error_description: None,
        });
        assert!(!ok);
    }

    #[tokio::test]
    async fn resolve_provider_mismatch_returns_false_and_does_not_dispatch() {
        let reg = OAuthRegistry::new();
        let _rx = reg.register("anthropic", "state-2", Duration::from_secs(30));
        let ok = reg.resolve(OAuthCallbackResult {
            provider: "github".into(), // wrong provider
            state: "state-2".into(),
            code: Some("x".into()),
            error: None,
            error_description: None,
        });
        assert!(!ok);
        // Entry is still consumed (defense-in-depth — a state is one-shot
        // even on a provider mismatch, to avoid replay).
        assert!(reg.is_empty());
    }

    #[tokio::test]
    async fn resolve_expired_returns_false() {
        let reg = OAuthRegistry::new();
        let _rx = reg.register("anthropic", "state-3", Duration::from_millis(1));
        tokio::time::sleep(Duration::from_millis(20)).await;
        let ok = reg.resolve(OAuthCallbackResult {
            provider: "anthropic".into(),
            state: "state-3".into(),
            code: Some("x".into()),
            error: None,
            error_description: None,
        });
        assert!(!ok);
    }

    #[tokio::test]
    async fn sweep_drops_expired_entries() {
        let reg = OAuthRegistry::new();
        let _ = reg.register("anthropic", "expired", Duration::from_millis(1));
        let _live = reg.register("anthropic", "alive", Duration::from_secs(60));
        tokio::time::sleep(Duration::from_millis(20)).await;
        reg.sweep_expired();
        assert_eq!(reg.len(), 1);
    }
}
