//! Recorded flow packages: discovery, parameter validation, execution, repairs.
//!
//! A "flow" is a browser workflow the user demonstrated once (Record & Replay)
//! that skill-creator compiled into a deterministic Monty python script. At
//! call time the LLM only extracts parameters and invokes `run_flow`; the
//! script runs with NO LLM in the loop (same executor as the headless
//! `NEVOFLUX_HEADLESS_SCRIPT` mode).
//!
//! Package layout inside a skill directory:
//!
//! ```text
//! <skill>/flows/<flow_name>/
//!   replay.py      -- Monty script defining `run(params)`
//!   flow.json      -- manifest: {name, description, version, recording_id, params_schema}
//!   trace.jsonl    -- original recording (kept for regeneration; not read here)
//!   repairs.jsonl  -- appended by report_flow_repair after LLM-fallback runs
//! ```

use std::path::PathBuf;

use serde::Deserialize;

/// Parsed `flow.json` manifest.
#[derive(Debug, Clone, Deserialize)]
pub struct FlowManifest {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub version: u32,
    #[serde(default)]
    pub recording_id: Option<String>,
    #[serde(default = "default_params_schema")]
    pub params_schema: serde_json::Value,
}

fn default_params_schema() -> serde_json::Value {
    serde_json::json!({"type": "object", "properties": {}})
}

/// A discovered flow package on disk.
#[derive(Debug, Clone)]
pub struct FlowPackage {
    pub manifest: FlowManifest,
    pub dir: PathBuf,
}

impl FlowPackage {
    pub fn script_path(&self) -> PathBuf {
        self.dir.join("replay.py")
    }

    pub fn repairs_path(&self) -> PathBuf {
        self.dir.join("repairs.jsonl")
    }
}

/// Scan `<skills_dir>/<skill>/flows/<flow>/flow.json` across the given skills
/// roots. Unreadable dirs and invalid manifests are skipped (warn-logged), so
/// one broken package never hides the rest.
pub fn discover_flows(skills_dirs: &[PathBuf]) -> Vec<FlowPackage> {
    let mut flows: Vec<FlowPackage> = Vec::new();
    for base in skills_dirs {
        let Ok(skills) = std::fs::read_dir(base) else {
            continue;
        };
        for skill in skills.flatten() {
            let flows_dir = skill.path().join("flows");
            let Ok(entries) = std::fs::read_dir(&flows_dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let dir = entry.path();
                let manifest_path = dir.join("flow.json");
                let Ok(raw) = std::fs::read_to_string(&manifest_path) else {
                    continue;
                };
                match serde_json::from_str::<FlowManifest>(&raw) {
                    Ok(manifest) => {
                        // First hit wins on duplicate names (mirrors skill
                        // loading precedence across skills dirs).
                        if !flows.iter().any(|f| f.manifest.name == manifest.name) {
                            flows.push(FlowPackage { manifest, dir });
                        }
                    }
                    Err(err) => {
                        tracing::warn!(
                            "flow manifest {} is invalid and was skipped: {err}",
                            manifest_path.display()
                        );
                    }
                }
            }
        }
    }
    flows
}

/// Find a flow by name across the default user skills directories.
pub fn find_flow(name: &str) -> Option<FlowPackage> {
    discover_flows(&nevoflux_skills::default_user_skills_dirs())
        .into_iter()
        .find(|f| f.manifest.name == name)
}

/// Minimal JSON-Schema-subset validation: `params` must be an object, every
/// `required` key present, no unknown keys, and each value must match the
/// declared primitive `type`. Intentionally hand-rolled — the schemas are
/// generated by skill-creator and stay flat, so a full validator dependency
/// is not warranted.
pub fn validate_params(
    schema: &serde_json::Value,
    params: &serde_json::Value,
) -> Result<(), String> {
    let Some(obj) = params.as_object() else {
        return Err("params must be a JSON object".into());
    };
    let mut errors: Vec<String> = Vec::new();

    if let Some(required) = schema.get("required").and_then(|r| r.as_array()) {
        for key in required.iter().filter_map(|k| k.as_str()) {
            if !obj.contains_key(key) {
                errors.push(format!("missing required param '{key}'"));
            }
        }
    }

    if let Some(props) = schema.get("properties").and_then(|p| p.as_object()) {
        for (key, value) in obj {
            let Some(spec) = props.get(key) else {
                errors.push(format!("unknown param '{key}'"));
                continue;
            };
            if let Some(ty) = spec.get("type").and_then(|t| t.as_str()) {
                let ok = match ty {
                    "string" => value.is_string(),
                    "number" => value.is_number(),
                    "integer" => value.is_i64() || value.is_u64(),
                    "boolean" => value.is_boolean(),
                    "array" => value.is_array(),
                    "object" => value.is_object(),
                    _ => true,
                };
                if !ok {
                    errors.push(format!("param '{key}' should be of type {ty}"));
                }
            }
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("; "))
    }
}

/// Append one repair-suggestion record to the flow's `repairs.jsonl`.
/// skill-creator reads this file on its next session and asks the user to
/// confirm before updating the script (no silent self-healing).
pub fn append_repair(flow: &FlowPackage, entry: &serde_json::Value) -> std::io::Result<()> {
    use std::io::Write;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(flow.repairs_path())?;
    writeln!(f, "{entry}")
}

use crate::agent::code_mode::CodeModeResult;
use crate::error::{DaemonError, Result as DaemonResult};
use crate::wasm::services::BrowserContext;

/// Instruction appended to every failure handoff so the calling LLM knows how
/// to take over and how to file the repair suggestion afterwards.
const HANDOFF_INSTRUCTION: &str = "The recorded flow script failed partway. The browser is still \
at the failure state (see handoff.url / handoff.tab_id when present). Take over now: use the \
browser tools to relocate the failed element (durable selectors first, then role+name) and finish \
the remaining steps of the workflow yourself. After the task is complete, call \
report_flow_repair with this flow's name, the failed step, and the selector or approach that \
worked, so the script can be fixed with user approval later.";

/// Wrap a flow script for execution: prepend `import json`, append a trailing
/// `run(json.loads("<params-json>"))` expression so the script's return value
/// lands in `CodeModeResult.result`. Params are double-JSON-encoded because a
/// raw JSON object is not a valid Python literal (`true` / `null`), while a
/// JSON *string* is a valid Python string literal (same trick as the headless
/// runner's task injection, one level up).
fn wrap_script(user_code: &str, params: &serde_json::Value) -> String {
    let params_json = serde_json::to_string(params).unwrap_or_else(|_| "{}".into());
    let params_literal = serde_json::to_string(&params_json).unwrap_or_else(|_| "\"{}\"".into());
    format!("import json\n{user_code}\n\nrun(json.loads({params_literal}))\n")
}

/// Convert a `CodeModeResult` into the tool-result string for the calling LLM.
///
/// - script returned a dict without `"ok": false` -> plain JSON passthrough
/// - script returned a handoff (`"ok": false`)    -> `status: script_failed` envelope
/// - Monty runtime error                          -> `status: script_error` envelope
fn format_flow_result(flow_name: &str, result: &CodeModeResult) -> String {
    if result.success {
        let value = match &result.result {
            Some(v) if !v.is_null() => v.clone(),
            _ => serde_json::json!({"ok": true, "output": result.output}),
        };
        let script_failed = value
            .get("ok")
            .map(|ok| ok == &serde_json::json!(false))
            .unwrap_or(false);
        if script_failed {
            serde_json::json!({
                "flow": flow_name,
                "status": "script_failed",
                "handoff": value,
                "instruction": HANDOFF_INSTRUCTION,
            })
            .to_string()
        } else {
            value.to_string()
        }
    } else {
        serde_json::json!({
            "flow": flow_name,
            "status": "script_error",
            "handoff": {
                "error": result.error.clone().unwrap_or_else(|| "flow script failed".into()),
                "output": result.output,
            },
            "instruction": HANDOFF_INSTRUCTION,
        })
        .to_string()
    }
}

/// Execute a flow's `replay.py` with already-validated params against the
/// bound browser. Synchronous by design — `execute_python_simple` does its own
/// `block_in_place + block_on`, exactly like the headless script runner.
pub fn execute_flow(
    flow: &FlowPackage,
    params: &serde_json::Value,
    browser_ctx: BrowserContext,
) -> DaemonResult<String> {
    let script_path = flow.script_path();
    let user_code = std::fs::read_to_string(&script_path).map_err(|e| {
        DaemonError::InternalError(format!(
            "run_flow: cannot read flow script {}: {e}",
            script_path.display()
        ))
    })?;
    let wrapped = wrap_script(&user_code, params);
    let result = crate::agent::code_mode::execute_python_simple(&wrapped, Some(browser_ctx));
    Ok(format_flow_result(&flow.manifest.name, &result))
}

/// Daemon-orchestrated dispatch for the recorded-flow tools, mirroring
/// `agent::tools::dispatch_recording_tool`. Called from both the direct-API
/// path (`agent_host::tool_call_dynamic`) and the ACP/MCP-bridge path
/// (`mcp_tool_executor::execute_mcp_tool`).
pub async fn dispatch_flow_tool(
    name: &str,
    arguments: &serde_json::Value,
    browser_ctx: Option<BrowserContext>,
) -> DaemonResult<String> {
    match name {
        "list_flows" => {
            let flows: Vec<serde_json::Value> =
                discover_flows(&nevoflux_skills::default_user_skills_dirs())
                    .into_iter()
                    .map(|f| {
                        serde_json::json!({
                            "name": f.manifest.name,
                            "description": f.manifest.description,
                            "params_schema": f.manifest.params_schema,
                        })
                    })
                    .collect();
            Ok(serde_json::json!({ "flows": flows }).to_string())
        }
        "run_flow" => {
            let flow_name = arguments
                .get("name")
                .and_then(|v| v.as_str())
                .ok_or_else(|| {
                    DaemonError::InternalError("run_flow: missing 'name' argument".into())
                })?;
            let params = arguments
                .get("params")
                .cloned()
                .unwrap_or_else(|| serde_json::json!({}));
            let Some(flow) = find_flow(flow_name) else {
                let available: Vec<String> =
                    discover_flows(&nevoflux_skills::default_user_skills_dirs())
                        .into_iter()
                        .map(|f| f.manifest.name)
                        .collect();
                return Ok(serde_json::json!({
                    "status": "unknown_flow",
                    "error": format!("no recorded flow named '{flow_name}'"),
                    "available_flows": available,
                })
                .to_string());
            };
            if let Err(e) = validate_params(&flow.manifest.params_schema, &params) {
                return Ok(serde_json::json!({
                    "status": "invalid_params",
                    "flow": flow.manifest.name,
                    "error": e,
                    "params_schema": flow.manifest.params_schema,
                })
                .to_string());
            }
            let ctx = browser_ctx.ok_or_else(|| {
                DaemonError::InternalError("run_flow: browser not available".into())
            })?;
            execute_flow(&flow, &params, ctx)
        }
        "report_flow_repair" => {
            let flow_name = arguments
                .get("flow")
                .and_then(|v| v.as_str())
                .ok_or_else(|| {
                    DaemonError::InternalError("report_flow_repair: missing 'flow' argument".into())
                })?;
            let Some(flow) = find_flow(flow_name) else {
                return Ok(serde_json::json!({
                    "status": "unknown_flow",
                    "error": format!("no recorded flow named '{flow_name}'"),
                })
                .to_string());
            };
            let entry = serde_json::json!({
                "failed_step": arguments.get("failed_step").cloned().unwrap_or(serde_json::Value::Null),
                "suggestion": arguments.get("suggestion").cloned().unwrap_or(serde_json::Value::Null),
                "reported_at_ms": std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_millis() as u64)
                    .unwrap_or(0),
            });
            append_repair(&flow, &entry).map_err(|e| {
                DaemonError::InternalError(format!(
                    "report_flow_repair: cannot write {}: {e}",
                    flow.repairs_path().display()
                ))
            })?;
            Ok(serde_json::json!({
                "status": "recorded",
                "flow": flow.manifest.name,
                "note": "Repair suggestion saved. skill-creator will ask the user to confirm the script update on its next session.",
            })
            .to_string())
        }
        other => Err(DaemonError::InternalError(format!(
            "dispatch_flow_tool: unknown flow tool '{other}'"
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};
    use tempfile::TempDir;

    fn write_flow(dir: &Path, skill: &str, flow: &str, manifest: &str) -> PathBuf {
        let flow_dir = dir.join(skill).join("flows").join(flow);
        std::fs::create_dir_all(&flow_dir).unwrap();
        std::fs::write(flow_dir.join("flow.json"), manifest).unwrap();
        std::fs::write(
            flow_dir.join("replay.py"),
            "def run(params):\n    return {\"ok\": True}\n",
        )
        .unwrap();
        flow_dir
    }

    const MANIFEST: &str = r#"{
        "name": "jira_ticket",
        "description": "Create a Jira ticket",
        "version": 1,
        "recording_id": "rec_1",
        "params_schema": {
            "type": "object",
            "properties": {
                "project": {"type": "string"},
                "title": {"type": "string"},
                "count": {"type": "integer"}
            },
            "required": ["project", "title"]
        }
    }"#;

    #[test]
    fn test_discover_flows_finds_manifest() {
        let tmp = TempDir::new().unwrap();
        write_flow(tmp.path(), "my-skill", "jira_ticket", MANIFEST);
        let flows = discover_flows(&[tmp.path().to_path_buf()]);
        assert_eq!(flows.len(), 1);
        assert_eq!(flows[0].manifest.name, "jira_ticket");
        assert_eq!(flows[0].manifest.description, "Create a Jira ticket");
        assert!(flows[0].script_path().ends_with("replay.py"));
    }

    #[test]
    fn test_discover_flows_skips_invalid_manifest() {
        let tmp = TempDir::new().unwrap();
        write_flow(tmp.path(), "my-skill", "bad", "not json at all");
        let flows = discover_flows(&[tmp.path().to_path_buf()]);
        assert!(flows.is_empty());
    }

    #[test]
    fn test_discover_flows_missing_dirs_ok() {
        let flows = discover_flows(&[PathBuf::from("/nonexistent/nowhere")]);
        assert!(flows.is_empty());
    }

    #[test]
    fn test_validate_params_ok() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let params = serde_json::json!({"project": "NEVO", "title": "t", "count": 3});
        assert!(validate_params(&m.params_schema, &params).is_ok());
    }

    #[test]
    fn test_validate_params_missing_required() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let err =
            validate_params(&m.params_schema, &serde_json::json!({"project": "NEVO"})).unwrap_err();
        assert!(err.contains("title"), "err was: {err}");
    }

    #[test]
    fn test_validate_params_wrong_type_and_unknown() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let err = validate_params(
            &m.params_schema,
            &serde_json::json!({"project": 1, "title": "t", "bogus": true}),
        )
        .unwrap_err();
        assert!(err.contains("project"), "err was: {err}");
        assert!(err.contains("bogus"), "err was: {err}");
    }

    #[test]
    fn test_validate_params_not_object() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        assert!(validate_params(&m.params_schema, &serde_json::json!("str")).is_err());
    }

    #[test]
    fn test_wrap_script_injects_params_via_json() {
        let wrapped = wrap_script(
            "def run(params):\n    return params[\"q\"]\n",
            &serde_json::json!({"q": "hello \"world\"", "flag": true, "n": null}),
        );
        assert!(wrapped.starts_with("import json\n"), "wrapped: {wrapped}");
        assert!(wrapped.contains("def run(params):"));
        assert!(wrapped.contains("run(json.loads("), "wrapped: {wrapped}");
        // The JSON payload must be double-encoded (a Python string literal).
        assert!(
            wrapped.contains("\\\"flag\\\": true") || wrapped.contains("\\\"flag\\\":true"),
            "wrapped: {wrapped}"
        );
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn test_execute_flow_returns_script_value() {
        // No browser tools needed by this script, so browser_ctx = None works
        // through execute_python_simple; exercise wrap + execute + format.
        let tmp = TempDir::new().unwrap();
        let dir = write_flow(
            tmp.path(),
            "my-skill",
            "echo",
            r#"{"name": "echo", "description": "", "version": 1,
                "params_schema": {"type": "object", "properties": {"q": {"type": "string"}}, "required": ["q"]}}"#,
        );
        std::fs::write(
            dir.join("replay.py"),
            "def run(params):\n    return {\"ok\": True, \"echo\": params[\"q\"]}\n",
        )
        .unwrap();
        let flow = FlowPackage {
            manifest: serde_json::from_str(
                &std::fs::read_to_string(dir.join("flow.json")).unwrap(),
            )
            .unwrap(),
            dir,
        };
        let code = std::fs::read_to_string(flow.script_path()).unwrap();
        let wrapped = wrap_script(&code, &serde_json::json!({"q": "hi"}));
        let result = tokio::task::spawn_blocking(move || {
            crate::agent::code_mode::execute_python_simple(&wrapped, None)
        })
        .await
        .unwrap();
        let formatted = format_flow_result("echo", &result);
        let v: serde_json::Value = serde_json::from_str(&formatted).unwrap();
        assert_eq!(v["ok"], serde_json::json!(true), "formatted: {formatted}");
        assert_eq!(v["echo"], serde_json::json!("hi"));
    }

    #[test]
    fn test_format_flow_result_wraps_script_handoff() {
        let result = crate::agent::code_mode::CodeModeResult::success(String::new()).with_result(
            serde_json::json!({
                "ok": false, "failed_step": 3, "step_label": "click submit",
                "url": "https://x/y", "tab_id": 2, "error": "no selector matched"
            }),
        );
        let formatted = format_flow_result("jira_ticket", &result);
        let v: serde_json::Value = serde_json::from_str(&formatted).unwrap();
        assert_eq!(v["status"], serde_json::json!("script_failed"));
        assert_eq!(v["flow"], serde_json::json!("jira_ticket"));
        assert_eq!(v["handoff"]["failed_step"], serde_json::json!(3));
        let instruction = v["instruction"].as_str().unwrap();
        assert!(
            instruction.contains("browser"),
            "instruction: {instruction}"
        );
        assert!(
            instruction.contains("report_flow_repair"),
            "instruction: {instruction}"
        );
    }

    #[test]
    fn test_format_flow_result_wraps_runtime_error() {
        let result = crate::agent::code_mode::CodeModeResult::fail("NameError: nope");
        let formatted = format_flow_result("jira_ticket", &result);
        let v: serde_json::Value = serde_json::from_str(&formatted).unwrap();
        assert_eq!(v["status"], serde_json::json!("script_error"));
        assert!(v["handoff"]["error"]
            .as_str()
            .unwrap()
            .contains("NameError"));
        assert!(v["instruction"]
            .as_str()
            .unwrap()
            .contains("report_flow_repair"));
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn test_dispatch_list_flows_and_errors() {
        // list_flows scans the real user skills dirs — just assert it returns
        // valid JSON with a "flows" array (machine may or may not have flows).
        let out = dispatch_flow_tool("list_flows", &serde_json::json!({}), None)
            .await
            .unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert!(v["flows"].is_array());

        // run_flow with a name that cannot exist -> Ok(json) with unknown_flow status
        let out = dispatch_flow_tool(
            "run_flow",
            &serde_json::json!({"name": "__no_such_flow__", "params": {}}),
            None,
        )
        .await
        .unwrap();
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["status"], serde_json::json!("unknown_flow"));

        // unknown dispatch name -> Err
        assert!(
            dispatch_flow_tool("bogus_tool", &serde_json::json!({}), None)
                .await
                .is_err()
        );
    }

    #[test]
    fn test_append_repair_appends_jsonl() {
        let tmp = TempDir::new().unwrap();
        let dir = write_flow(tmp.path(), "my-skill", "jira_ticket", MANIFEST);
        let flow = FlowPackage {
            manifest: serde_json::from_str(MANIFEST).unwrap(),
            dir,
        };
        append_repair(
            &flow,
            &serde_json::json!({"failed_step": 3, "suggestion": "s1"}),
        )
        .unwrap();
        append_repair(
            &flow,
            &serde_json::json!({"failed_step": 3, "suggestion": "s2"}),
        )
        .unwrap();
        let content = std::fs::read_to_string(flow.repairs_path()).unwrap();
        let lines: Vec<&str> = content.lines().collect();
        assert_eq!(lines.len(), 2);
        assert!(lines[0].contains("s1"));
        assert!(lines[1].contains("s2"));
    }
}
