//! Recorded flow packages: discovery, parameter validation, execution, repairs.
//!
//! A "flow" is a browser workflow the user demonstrated once (Record & Replay)
//! that skill-creator compiled into a deterministic Monty python script. At
//! call time the LLM only extracts parameters and invokes `run_flow`; the
//! script runs with NO LLM in the loop (same executor as the headless
//! `NEVOFLUX_HEADLESS_SCRIPT` mode).
//!
//! Package layout inside a skill directory:
//!
//! ```text
//! <skill>/flows/<flow_name>/
//!   replay.py      -- Monty script defining `run(params)`
//!   flow.json      -- manifest: {name, description, version, recording_id, params_schema}
//!   trace.jsonl    -- original recording (kept for regeneration; not read here)
//!   repairs.jsonl  -- appended by report_flow_repair after LLM-fallback runs
//! ```

use std::path::PathBuf;

use serde::Deserialize;

/// Parsed `flow.json` manifest.
#[derive(Debug, Clone, Deserialize)]
pub struct FlowManifest {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub version: u32,
    #[serde(default)]
    pub recording_id: Option<String>,
    #[serde(default = "default_params_schema")]
    pub params_schema: serde_json::Value,
}

fn default_params_schema() -> serde_json::Value {
    serde_json::json!({"type": "object", "properties": {}})
}

/// A discovered flow package on disk.
#[derive(Debug, Clone)]
pub struct FlowPackage {
    pub manifest: FlowManifest,
    pub dir: PathBuf,
}

impl FlowPackage {
    pub fn script_path(&self) -> PathBuf {
        self.dir.join("replay.py")
    }

    pub fn repairs_path(&self) -> PathBuf {
        self.dir.join("repairs.jsonl")
    }
}

/// Scan `<skills_dir>/<skill>/flows/<flow>/flow.json` across the given skills
/// roots. Unreadable dirs and invalid manifests are skipped (warn-logged), so
/// one broken package never hides the rest.
pub fn discover_flows(skills_dirs: &[PathBuf]) -> Vec<FlowPackage> {
    let mut flows: Vec<FlowPackage> = Vec::new();
    for base in skills_dirs {
        let Ok(skills) = std::fs::read_dir(base) else {
            continue;
        };
        for skill in skills.flatten() {
            let flows_dir = skill.path().join("flows");
            let Ok(entries) = std::fs::read_dir(&flows_dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let dir = entry.path();
                let manifest_path = dir.join("flow.json");
                let Ok(raw) = std::fs::read_to_string(&manifest_path) else {
                    continue;
                };
                match serde_json::from_str::<FlowManifest>(&raw) {
                    Ok(manifest) => {
                        // First hit wins on duplicate names (mirrors skill
                        // loading precedence across skills dirs).
                        if !flows.iter().any(|f| f.manifest.name == manifest.name) {
                            flows.push(FlowPackage { manifest, dir });
                        }
                    }
                    Err(err) => {
                        tracing::warn!(
                            "flow manifest {} is invalid and was skipped: {err}",
                            manifest_path.display()
                        );
                    }
                }
            }
        }
    }
    flows
}

/// Find a flow by name across the default user skills directories.
pub fn find_flow(name: &str) -> Option<FlowPackage> {
    discover_flows(&nevoflux_skills::default_user_skills_dirs())
        .into_iter()
        .find(|f| f.manifest.name == name)
}

/// Minimal JSON-Schema-subset validation: `params` must be an object, every
/// `required` key present, no unknown keys, and each value must match the
/// declared primitive `type`. Intentionally hand-rolled — the schemas are
/// generated by skill-creator and stay flat, so a full validator dependency
/// is not warranted.
pub fn validate_params(
    schema: &serde_json::Value,
    params: &serde_json::Value,
) -> Result<(), String> {
    let Some(obj) = params.as_object() else {
        return Err("params must be a JSON object".into());
    };
    let mut errors: Vec<String> = Vec::new();

    if let Some(required) = schema.get("required").and_then(|r| r.as_array()) {
        for key in required.iter().filter_map(|k| k.as_str()) {
            if !obj.contains_key(key) {
                errors.push(format!("missing required param '{key}'"));
            }
        }
    }

    if let Some(props) = schema.get("properties").and_then(|p| p.as_object()) {
        for (key, value) in obj {
            let Some(spec) = props.get(key) else {
                errors.push(format!("unknown param '{key}'"));
                continue;
            };
            if let Some(ty) = spec.get("type").and_then(|t| t.as_str()) {
                let ok = match ty {
                    "string" => value.is_string(),
                    "number" => value.is_number(),
                    "integer" => value.is_i64() || value.is_u64(),
                    "boolean" => value.is_boolean(),
                    "array" => value.is_array(),
                    "object" => value.is_object(),
                    _ => true,
                };
                if !ok {
                    errors.push(format!("param '{key}' should be of type {ty}"));
                }
            }
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("; "))
    }
}

/// Append one repair-suggestion record to the flow's `repairs.jsonl`.
/// skill-creator reads this file on its next session and asks the user to
/// confirm before updating the script (no silent self-healing).
pub fn append_repair(flow: &FlowPackage, entry: &serde_json::Value) -> std::io::Result<()> {
    use std::io::Write;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(flow.repairs_path())?;
    writeln!(f, "{entry}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};
    use tempfile::TempDir;

    fn write_flow(dir: &Path, skill: &str, flow: &str, manifest: &str) -> PathBuf {
        let flow_dir = dir.join(skill).join("flows").join(flow);
        std::fs::create_dir_all(&flow_dir).unwrap();
        std::fs::write(flow_dir.join("flow.json"), manifest).unwrap();
        std::fs::write(
            flow_dir.join("replay.py"),
            "def run(params):\n    return {\"ok\": True}\n",
        )
        .unwrap();
        flow_dir
    }

    const MANIFEST: &str = r#"{
        "name": "jira_ticket",
        "description": "Create a Jira ticket",
        "version": 1,
        "recording_id": "rec_1",
        "params_schema": {
            "type": "object",
            "properties": {
                "project": {"type": "string"},
                "title": {"type": "string"},
                "count": {"type": "integer"}
            },
            "required": ["project", "title"]
        }
    }"#;

    #[test]
    fn test_discover_flows_finds_manifest() {
        let tmp = TempDir::new().unwrap();
        write_flow(tmp.path(), "my-skill", "jira_ticket", MANIFEST);
        let flows = discover_flows(&[tmp.path().to_path_buf()]);
        assert_eq!(flows.len(), 1);
        assert_eq!(flows[0].manifest.name, "jira_ticket");
        assert_eq!(flows[0].manifest.description, "Create a Jira ticket");
        assert!(flows[0].script_path().ends_with("replay.py"));
    }

    #[test]
    fn test_discover_flows_skips_invalid_manifest() {
        let tmp = TempDir::new().unwrap();
        write_flow(tmp.path(), "my-skill", "bad", "not json at all");
        let flows = discover_flows(&[tmp.path().to_path_buf()]);
        assert!(flows.is_empty());
    }

    #[test]
    fn test_discover_flows_missing_dirs_ok() {
        let flows = discover_flows(&[PathBuf::from("/nonexistent/nowhere")]);
        assert!(flows.is_empty());
    }

    #[test]
    fn test_validate_params_ok() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let params = serde_json::json!({"project": "NEVO", "title": "t", "count": 3});
        assert!(validate_params(&m.params_schema, &params).is_ok());
    }

    #[test]
    fn test_validate_params_missing_required() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let err = validate_params(&m.params_schema, &serde_json::json!({"project": "NEVO"}))
            .unwrap_err();
        assert!(err.contains("title"), "err was: {err}");
    }

    #[test]
    fn test_validate_params_wrong_type_and_unknown() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        let err = validate_params(
            &m.params_schema,
            &serde_json::json!({"project": 1, "title": "t", "bogus": true}),
        )
        .unwrap_err();
        assert!(err.contains("project"), "err was: {err}");
        assert!(err.contains("bogus"), "err was: {err}");
    }

    #[test]
    fn test_validate_params_not_object() {
        let m: FlowManifest = serde_json::from_str(MANIFEST).unwrap();
        assert!(validate_params(&m.params_schema, &serde_json::json!("str")).is_err());
    }

    #[test]
    fn test_append_repair_appends_jsonl() {
        let tmp = TempDir::new().unwrap();
        let dir = write_flow(tmp.path(), "my-skill", "jira_ticket", MANIFEST);
        let flow = FlowPackage {
            manifest: serde_json::from_str(MANIFEST).unwrap(),
            dir,
        };
        append_repair(&flow, &serde_json::json!({"failed_step": 3, "suggestion": "s1"})).unwrap();
        append_repair(&flow, &serde_json::json!({"failed_step": 3, "suggestion": "s2"})).unwrap();
        let content = std::fs::read_to_string(flow.repairs_path()).unwrap();
        let lines: Vec<&str> = content.lines().collect();
        assert_eq!(lines.len(), 2);
        assert!(lines[0].contains("s1"));
        assert!(lines[1].contains("s2"));
    }
}
