// Pinned engine release data — GENERATED by
// `scripts/engine-release/gen_release_rs.py`, do not hand-edit.
//
// Included textually by `release.rs`, which owns the struct definitions, the
// resolution logic and the tests. Only the mechanical part — the table staged
// from a verified `staged.json` — is generated.

/// Staged assets this table was generated from, in total.
///
/// `STAGED_ARCHIVE_COUNT` + `STAGED_CUDART_COUNT` + 1 source + 1 skipped
/// manifest. `release.rs`'s tests assert the archive and cudart counts against
/// hand-written literals rather than against these constants: two generated
/// values agreeing with each other proves nothing, whereas a literal a human
/// must update is a real pin on a re-pin.
pub const STAGED_ASSET_COUNT: usize = 28;
/// [`EngineArchive`]s in [`ENGINE_PINNED`].
pub const STAGED_ARCHIVE_COUNT: usize = 24;
/// [`CudartArchive`]s in [`ENGINE_PINNED`].
pub const STAGED_CUDART_COUNT: usize = 2;

/// The engine release this daemon currently installs.
pub const ENGINE_PINNED: EngineRelease = EngineRelease {
    tag: "b10909-mix-bea84f7",
    upstream_tag: "b10909",
    archives: &[
        EngineArchive {
            platform: "linux-arm64",
            backend: Backend::Cpu,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-arm64-cpu.tar.gz",
                bytes: 13309585,
                sha256: "e9c3da377c77e3e86860949e478652ea4b39e4075e3163c7c20d4e493db11c49",
            },
        },
        EngineArchive {
            platform: "linux-arm64",
            backend: Backend::Vulkan,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-arm64-vulkan.tar.gz",
                bytes: 26573241,
                sha256: "812c4ac64f33eeb05b8c3f9507df33b931e90f0953038bcd1bb92e1df807676c",
            },
        },
        EngineArchive {
            platform: "linux-arm64",
            backend: Backend::Cuda,
            variant: Some("cuda13-portable"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-arm64-cuda13-portable.tar.gz",
                bytes: 193998880,
                sha256: "6500020f5cd329a13cbd2c9fc556113d9110a2cfc38ec3d67ec97ffdbdd029dc",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cpu,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cpu.tar.gz",
                bytes: 16985016,
                sha256: "db80dff1c360cf900ea1ae4f9622c1d9a3d76b38892cfd02284bcb53cfb66071",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Vulkan,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-vulkan.tar.gz",
                bytes: 30330026,
                sha256: "d90a92d8bcf1cc5102ca64b2587a0f737dee08d8bae8f7c9a3a91fd63dbb4b13",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-legacy"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda12-legacy.tar.gz",
                bytes: 39740808,
                sha256: "c79538e26020345655bc64e65c7b637991ff4e844718830c9f2347dc215e3202",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-newer"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda12-newer.tar.gz",
                bytes: 235831870,
                sha256: "d309ac073f69b993d43e0a2fe3696a2acfc7a2b565a10152961702c4ab8a6ea1",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-older"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda12-older.tar.gz",
                bytes: 226827793,
                sha256: "0c477165533c3371b57c2ea19a6c560011397bbaae7fe80b813de389b0671a66",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-portable"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda12-portable.tar.gz",
                bytes: 359055008,
                sha256: "636321afe0d1be88579410f765a1924493f526726b42b989a6ead24f69923856",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-newer"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda13-newer.tar.gz",
                bytes: 234952406,
                sha256: "dcc5ec3ade0846b1dea31680e6ca585658db3e8b185214856d4e161117bfac0a",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-older"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda13-older.tar.gz",
                bytes: 187393632,
                sha256: "72a7c83ae72f8a163addde0c23ad95ad2e60fdfe6d594328d44afca2d534b533",
            },
        },
        EngineArchive {
            platform: "linux-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-portable"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-linux-x64-cuda13-portable.tar.gz",
                bytes: 318732902,
                sha256: "aa5632165d5b0cc50f59e2fdad1c9571f5202915d8b730b2379c05d93d04833e",
            },
        },
        EngineArchive {
            platform: "macos-arm64",
            backend: Backend::Metal,
            variant: None,
            asset: EngineAsset {
                name: "llama-b10909-mix-bea84f7-bin-macos-arm64.tar.gz",
                bytes: 11352244,
                sha256: "211bc7e23d58e12981fed767648796140e8bc623a66aae3661e36d399f1b98d6",
            },
        },
        EngineArchive {
            platform: "macos-x64",
            backend: Backend::Metal,
            variant: None,
            asset: EngineAsset {
                name: "llama-b10909-mix-bea84f7-bin-macos-x64.tar.gz",
                bytes: 11368028,
                sha256: "dee0a54fbad9c70ecbc6a2d56e65f27884926a4a9d776aa4481aa49ca68912c5",
            },
        },
        EngineArchive {
            platform: "windows-arm64",
            backend: Backend::Cpu,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-arm64-cpu.zip",
                bytes: 12452370,
                sha256: "413412f081012098df06e60f7f598f727b1ce1ad52dc3be56a226e851c8593d9",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cpu,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cpu.zip",
                bytes: 19072438,
                sha256: "59fb88ef5265bd677f7794e361914f70d03aedd0051888a6b085ce0b7bf1bedf",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Vulkan,
            variant: None,
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-vulkan.zip",
                bytes: 26921781,
                sha256: "3e0d99b9a3ae22a943ac49259b88a1c9736c4efcf1be7d54ed1b40933d18307a",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-legacy"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda12-legacy.zip",
                bytes: 36700839,
                sha256: "ecef36d8eb6a4c1ef88335e120f493c3b61dd5c9ba000d2b50b1667c0bf6a692",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-newer"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda12-newer.zip",
                bytes: 232429298,
                sha256: "786917c05e9a3ed2715df26c0c12b280745290daedc3a95030d8df50630c73d4",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-older"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda12-older.zip",
                bytes: 223481669,
                sha256: "ebebd57af9821171ef66e39051d36cfdaf2059c6ff0e42d50a6958eb505e89cd",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda12-portable"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda12-portable.zip",
                bytes: 355472684,
                sha256: "7518f626d80ccc002831ad2536f2cb7b233e0fe2268118e792c409f84d0b6d3a",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-newer"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda13-newer.zip",
                bytes: 231401052,
                sha256: "ff81f814df21f68324505d90e46add838f5072d7ec970f0a5da8448c4cd3432e",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-older"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda13-older.zip",
                bytes: 183728712,
                sha256: "5ebe36ef408d5affd19bbf804cfa1980c9cc59856a8f6a3abacf339af19cf96c",
            },
        },
        EngineArchive {
            platform: "windows-x64",
            backend: Backend::Cuda,
            variant: Some("cuda13-portable"),
            asset: EngineAsset {
                name: "app-b10909-mix-bea84f7-windows-x64-cuda13-portable.zip",
                bytes: 315168227,
                sha256: "7425a396e62d7c0642122069c41a26ed5faa47b85c7c4d2f073f82e10b5238c4",
            },
        },
    ],
    cudart: &[
        CudartArchive {
            runtime: "12.4",
            asset: EngineAsset {
                name: "cudart-llama-bin-win-cuda-12.4-x64.zip",
                bytes: 391443627,
                sha256: "8c79a9b226de4b3cacfd1f83d24f962d0773be79f1e7b75c6af4ded7e32ae1d6",
            },
        },
        CudartArchive {
            runtime: "13.3",
            asset: EngineAsset {
                name: "cudart-llama-bin-win-cuda-13.3-x64.zip",
                bytes: 390970417,
                sha256: "1462a050eb4c684921ba51dcc4cc488a036674c3e73e9945ee705b854808d03e",
            },
        },
    ],
    source: EngineAsset {
        name: "llama.cpp-source-b10909-mix-bea84f7.tar.gz",
        bytes: 37739417,
        sha256: "9d46c7ce4da17fa584df7d906209ff79f2b827a97b9fe57cd9652b29c55a6ca5",
    },
};

/// Older pinned releases still accepted for an existing install (so a
/// machine already running an older engine isn't forced to redownload on
/// every daemon update). Empty for this, the first pinned tag.
pub const ENGINE_COMPATIBLE: &[EngineRelease] = &[];
